export { WritingPage } from './components/topics/WritingPage'
export { WritingHeader } from './components/topics/WritingHeader'
export { WritingTopic } from './components/topics/WritingTopic'
export { WritingLesson } from './components/lesson/WritingLesson'
export { getWritingData, getWritingLesson, getWritingResult } from './services/writingService'