export { SpeakingPage } from './components/topics/SpeakingPage'
export { SpeakingHeader } from './components/topics/SpeakingHeader'
export { SpeakingTopic } from './components/topics/SpeakingTopic'
export { SpeakingLessonPage } from './components/lesson/SpeakingLessonPage'
export { getSpeakingData, getSpeakingLesson, getSpeakingResult } from './services/speakingService'
export { ResultSpeakingPage } from './components/result/ResultSpeakingPage'